##-----------------------------------------------------------
## Configuração - Spring Datasource
##-----------------------------------------------------------
server:
  port: 7009
  servlet:
    context-path: /api-monitor-prometheus
spring:
  h2:
    console:
      enabled: true
      path: /h2-console 
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
  properties:
        hibernate:
            dialect: org.hibernate.dialect.H2Dialect
  datasource:
    platform: h2
    url: jdbc:h2:file:C:\Users\nofre\test
    driverClassName: org.h2.Driver
    username: sa
    password: admin

##-----------------------------------------------------------
## Configuração - Spring Boot Actuator
##-----------------------------------------------------------
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: false
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

##-----------------------------------------------------------
## Configuração - Prometheus
##-----------------------------------------------------------
global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheusJob'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090'] #Servidor prometheus
  - job_name: 'spring-monitoring-demo'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:7009'] #Servidor da minha aplicação    
