##-----------------------------------------------------------
## Configuração - Prometheus
##-----------------------------------------------------------
global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'Projeto: java spring boot actuator prometheus grafana'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090'] #Servidor prometheus
  - job_name: 'spring-monitoring-demo'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:7009'] #Servidor da minha aplicação  